import Head from "next/head";
import { Column } from "~/components/column";
import { Task } from "~/components/task";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row justify-center gap-4 pt-8">
        <Column title="Todo">
          <Task title="Organize Living Room" />
          <Task title="Organize Living Room" />
          <Task title="Organize Living Room" />
        </Column>
        <Column title="In Progress" />
        <Column title="In Review" />
        <Column title="Done" />
      </main>
    </>
  );
}
