import Head from "next/head";
import { TaskColumn } from "~/components/taskColumn";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="p-4">
          <div className="flex flex-row gap-4">
            <TaskColumn title="Todo" taskState="todo" />
            <TaskColumn title="In Progress" taskState="inProgress" />
            <TaskColumn title="In Review" taskState="inReview" />
            <TaskColumn title="Done" taskState="done" />
          </div>
        </div>
      </main>
    </>
  );
}
